Repository php-enqueue/enqueue-dev, pull requests merged in 2018-12, with the labels that each got.

#666 [sqs] Add ability to use another aws account per queue.
  docs/transport/sqs.md
  pkg/sqs/SqsContext.php
  pkg/sqs/SqsDestination.php
  pkg/sqs/Tests/Spec/SqsSendToAndReceiveFromQueueTest.php
  pkg/sqs/Tests/Spec/SqsSendToAndReceiveNoWaitFromQueueTest.php
  pkg/sqs/Tests/Spec/SqsSendToAndReceiveNoWaitFromTopicTest.php
  pkg/sqs/Tests/Spec/SqsSendToTopicAndReceiveFromQueueTest.php
  pkg/sqs/Tests/Spec/SqsSendToTopicAndReceiveNoWaitFromQueueTest.php
  pkg/sqs/Tests/SqsContextTest.php
Labels: 0.9, enhancement

#671 [fs] Do not throw error in jsonUnserialize on deprecation notice
  pkg/fs/FsContext.php
Labels: 0.9, bug

#694 Fix async command\event pkgs
  pkg/async-command/DependencyInjection/AsyncCommandExtension.php
  pkg/async-command/Resources/config/services.yml
  pkg/async-command/RunCommandProcessor.php
  pkg/async-command/Tests/RunCommandProcessorTest.php
  pkg/async-event-dispatcher/AsyncProcessor.php
  pkg/async-event-dispatcher/DependencyInjection/AsyncEventDispatcherExtension.php
  pkg/async-event-dispatcher/Resources/config/services.yml
  pkg/enqueue-bundle/Tests/Functional/App/config/config.yml
  pkg/enqueue-bundle/Tests/Functional/Events/AsyncProcessorTest.php
  pkg/enqueue-bundle/Tests/Functional/RoutesCommandTest.php
Labels: bug

#702 [client] Fix SetRouterProeprtiesExtension should skip no topic messages.
  pkg/enqueue/Client/ConsumptionExtension/SetRouterPropertiesExtension.php
  pkg/enqueue/Tests/Client/ConsumptionExtension/SetRouterPropertiesExtensionTest.php
Labels: bug

#701 [client] Fix Exclusive Command Extension ignores route queue prefix option.
  pkg/enqueue/Client/ConsumptionExtension/ExclusiveCommandExtension.php
  pkg/enqueue/Tests/Client/ConsumptionExtension/ExclusiveCommandExtensionTest.php
Labels: bug

#703 [client] sendToProcessor should able to send message to router processor.
  pkg/enqueue/Client/Driver/GenericDriver.php
  pkg/enqueue/Tests/Client/Driver/GenericDriverTestsTrait.php
Labels: bug
