Repository php-enqueue/enqueue-dev, pull requests merged in 2018-11, with the labels that each got.

#611 [client][bundle] Take queue prefix into account while queue binding.
  pkg/enqueue/Symfony/Client/ConsumeCommand.php
  pkg/enqueue/Symfony/Client/DependencyInjection/AnalyzeRouteCollectionPass.php
  pkg/enqueue/Tests/Symfony/Client/ConsumeCommandTest.php
  pkg/enqueue/Tests/Symfony/Client/DependencyInjection/AnalyzeRouteCollectionPassTest.php
Labels: bug

#612 [fs] Use enqueue/dsn to parse DSN
  docs/transport/filesystem.md
  pkg/dsn/Dsn.php
  pkg/dsn/Tests/DsnTest.php
  pkg/fs/FsConnectionFactory.php
  pkg/fs/Tests/FsConnectionFactoryConfigTest.php
  pkg/fs/composer.json
Labels: bug

#628 [bundle] Multi Client Configuration
  docs/bundle/async_commands.md
  docs/bundle/async_events.md
  docs/bundle/config_reference.md
  docs/bundle/debugging.md
  docs/bundle/functional_testing.md
  docs/bundle/job_queue.md
  docs/bundle/quick_tour.md
  pkg/async-command/DependencyInjection/AsyncCommandExtension.php
  pkg/enqueue-bundle/DependencyInjection/Configuration.php
  pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
  pkg/enqueue-bundle/Profiler/MessageQueueCollector.php
  pkg/enqueue-bundle/Resources/config/client.yml
  pkg/enqueue-bundle/Resources/config/extensions/doctrine_clear_identity_map_extension.yml
  pkg/enqueue-bundle/Resources/config/extensions/doctrine_ping_connection_extension.yml
  pkg/enqueue-bundle/Resources/config/extensions/reply_extension.yml
  pkg/enqueue-bundle/Resources/config/extensions/signal_extension.yml
  pkg/enqueue-bundle/Resources/config/services.yml
  pkg/enqueue-bundle/Resources/views/Profiler/panel.html.twig
  pkg/enqueue-bundle/Tests/Functional/App/CustomAppKernel.php
  pkg/enqueue-bundle/Tests/Functional/App/config/config.yml
  pkg/enqueue-bundle/Tests/Functional/Events/AsyncListenerTest.php
  pkg/enqueue-bundle/Tests/Functional/Events/AsyncProcessorTest.php
  pkg/enqueue-bundle/Tests/Functional/Events/AsyncSubscriberTest.php
  pkg/enqueue-bundle/Tests/Functional/Job/CalculateRootJobStatusProcessorTest.php
  pkg/enqueue-bundle/Tests/Functional/Job/DependentJobServiceTest.php
  pkg/enqueue-bundle/Tests/Functional/Job/JobRunnerTest.php
  pkg/enqueue-bundle/Tests/Functional/Job/JobStorageTest.php
  pkg/enqueue-bundle/Tests/Functional/RoutesCommandTest.php
  pkg/enqueue-bundle/Tests/Functional/UseCasesTest.php
  pkg/enqueue-bundle/Tests/Unit/DependencyInjection/ConfigurationTest.php
  pkg/enqueue-bundle/Tests/Unit/DependencyInjection/EnqueueExtensionTest.php
  pkg/enqueue-bundle/Tests/Unit/Profiler/MessageQueueCollectorTest.php
  pkg/enqueue/Client/TraceableProducer.php
  pkg/enqueue/Symfony/Client/ConsumeCommand.php
  pkg/enqueue/Symfony/Client/DependencyInjection/ClientFactory.php
  pkg/enqueue/Symfony/Client/ProduceCommand.php
  pkg/enqueue/Symfony/Client/RoutesCommand.php
  pkg/enqueue/Symfony/Client/SetupBrokerCommand.php
  pkg/enqueue/Symfony/Consumption/ConfigurableConsumeCommand.php
  pkg/enqueue/Symfony/Consumption/ConsumeCommand.php
  pkg/enqueue/Symfony/DependencyInjection/TransportFactory.php
  pkg/enqueue/Symfony/DiUtils.php
  pkg/enqueue/Symfony/MissingComponentFactory.php
  pkg/enqueue/Tests/Client/TraceableProducerTest.php
  pkg/enqueue/Tests/Symfony/Client/ConsumeCommandTest.php
  pkg/enqueue/Tests/Symfony/Client/ProduceCommandTest.php
  pkg/enqueue/Tests/Symfony/Client/RoutesCommandTest.php
  pkg/enqueue/Tests/Symfony/Client/SetupBrokerCommandTest.php
  pkg/enqueue/Tests/Symfony/Consumption/ConfigurableConsumeCommandTest.php
  pkg/enqueue/Tests/Symfony/Consumption/ConsumeCommandTest.php
  pkg/enqueue/Tests/Symfony/DependencyInjection/TransportFactoryTest.php
  pkg/monitoring/GenericStatsStorageFactory.php
  pkg/monitoring/Resources.php
  pkg/monitoring/StatsStorageFactory.php
  pkg/monitoring/Symfony/DependencyInjection/MonitoringFactory.php
  pkg/monitoring/Tests/GenericStatsStorageFactoryTest.php
  pkg/simple-client/SimpleClient.php
Labels: enhancement

#613 [dbal] Use concurrent fetch message approach (no transaction, no pessimistic lock)
  pkg/dbal/DbalConsumer.php
  pkg/dbal/DbalConsumerHelperTrait.php
  pkg/dbal/DbalContext.php
  pkg/dbal/DbalMessage.php
  pkg/dbal/DbalProducer.php
  pkg/dbal/DbalSubscriptionConsumer.php
  pkg/dbal/Tests/DbalConsumerTest.php
  pkg/dbal/Tests/Functional/DbalConsumerTest.php
Labels: enhancement

#641 [bundle] Add BC for topic\command subscribers.
  pkg/enqueue/Client/TopicSubscriberInterface.php
  pkg/enqueue/Symfony/Client/DependencyInjection/BuildCommandSubscriberRoutesPass.php
  pkg/enqueue/Symfony/Client/DependencyInjection/BuildTopicSubscriberRoutesPass.php
  pkg/enqueue/Tests/Symfony/Client/DependencyInjection/BuildCommandSubscriberRoutesPassTest.php
  pkg/enqueue/Tests/Symfony/Client/DependencyInjection/BuildTopicSubscriberRoutesPassTest.php
Labels: enhancement

#643 [dsn] Parse DSN Cluster
  docs/dsn.md
  pkg/amqp-tools/ConnectionConfig.php
  pkg/dsn/Dsn.php
  pkg/dsn/QueryBag.php
  pkg/dsn/Tests/DsnTest.php
  pkg/enqueue/Client/DriverFactory.php
  pkg/enqueue/ConnectionFactoryFactory.php
  pkg/fs/FsConnectionFactory.php
  pkg/gps/GpsConnectionFactory.php
  pkg/monitoring/GenericStatsStorageFactory.php
  pkg/monitoring/InfluxDbStorage.php
  pkg/monitoring/WampStorage.php
  pkg/redis/RedisConnectionFactory.php
  pkg/sqs/SqsConnectionFactory.php
  pkg/stomp/StompConnectionFactory.php
  pkg/stomp/Tests/StompConnectionFactoryConfigTest.php
  pkg/test/RabbitManagementExtensionTrait.php
  pkg/wamp/WampConnectionFactory.php
Labels: enhancement

#646 Rework DriverFactory, add separator option to Client Config.
  docs/bundle/config_reference.md
  docs/laravel/quick_tour.md
  pkg/enqueue-bundle/Tests/Functional/App/CustomAppKernel.php
  pkg/enqueue-bundle/Tests/Unit/DependencyInjection/ConfigurationTest.php
  pkg/enqueue/Client/Config.php
  pkg/enqueue/Client/DriverFactory.php
  pkg/enqueue/Client/DriverFactoryInterface.php
  pkg/enqueue/Symfony/Client/DependencyInjection/ClientFactory.php
  pkg/enqueue/Tests/Client/ConfigTest.php
  pkg/enqueue/Tests/Client/ConsumptionExtension/SetRouterPropertiesExtensionTest.php
  pkg/enqueue/Tests/Client/Driver/GenericDriverTestsTrait.php
  pkg/enqueue/Tests/Client/Driver/RabbitMqStompDriverTest.php
  pkg/enqueue/Tests/Client/DriverFactoryTest.php
  pkg/enqueue/Tests/Client/ProducerSendCommandTest.php
  pkg/enqueue/Tests/Client/ProducerSendEventTest.php
  pkg/enqueue/Tests/Symfony/Client/DependencyInjection/ClientFactoryTest.php
  pkg/simple-client/SimpleClient.php
  pkg/simple-client/Tests/Functional/SimpleClientTest.php
  pkg/wamp/Tests/Functional/WampConsumerTest.php
Labels: enhancement

#658 [amqp][lib] Improve heartbeat handling. Introduce heartbeat on tick. Fixes "Invalid frame type 65" and "Broken pipe or closed connection"
  pkg/amqp-lib/AmqpConnectionFactory.php
  pkg/amqp-lib/AmqpContext.php
  pkg/amqp-lib/AmqpSubscriptionConsumer.php
  pkg/amqp-lib/Tests/AmqpContextTest.php
  pkg/amqp-lib/Tests/AmqpSubscriptionConsumerTest.php
  pkg/amqp-lib/Tests/Functional/AmqpSubscriptionConsumerWithHeartbeatOnTickTest.php
  pkg/amqp-lib/composer.json
Labels: enhancement

#660 Allow installing stable dependencies.
  pkg/amqp-bunny/composer.json
  pkg/amqp-ext/composer.json
  pkg/amqp-lib/composer.json
  pkg/async-command/composer.json
  pkg/async-event-dispatcher/composer.json
  pkg/enqueue-bundle/composer.json
  pkg/enqueue/composer.json
  pkg/fs/composer.json
  pkg/gps/composer.json
  pkg/job-queue/composer.json
  pkg/monitoring/composer.json
  pkg/redis/composer.json
  pkg/simple-client/composer.json
  pkg/sqs/composer.json
  pkg/stomp/composer.json
  pkg/wamp/composer.json
Labels: 0.9, bug

#662 [sqs] Use a queue created in another AWS account.
  pkg/sqs/SqsConnectionFactory.php
  pkg/sqs/SqsContext.php
  pkg/sqs/Tests/Spec/CreateSqsQueueTrait.php
  pkg/sqs/Tests/Spec/SqsSendAndReceiveDelayedMessageFromQueueTest.php
  pkg/sqs/Tests/Spec/SqsSendToAndReceiveFromQueueTest.php
  pkg/sqs/Tests/Spec/SqsSendToAndReceiveFromTopicTest.php
  pkg/sqs/Tests/Spec/SqsSendToAndReceiveNoWaitFromQueueTest.php
  pkg/sqs/Tests/Spec/SqsSendToAndReceiveNoWaitFromTopicTest.php
  pkg/sqs/Tests/Spec/SqsSendToTopicAndReceiveFromQueueTest.php
  pkg/sqs/Tests/Spec/SqsSendToTopicAndReceiveNoWaitFromQueueTest.php
  pkg/sqs/Tests/SqsConnectionFactoryConfigTest.php
  pkg/sqs/Tests/SqsConnectionFactoryTest.php
  pkg/sqs/Tests/SqsContextTest.php
Labels: 0.9, enhancement

#665 [dbal] Use ordered bytes time uuid codec on message id decode.
  pkg/dbal/DbalContext.php
Labels: 0.9, bug
